all:
  vars:
    runenv: qal
    ansible_become: yes
    ansible_become_method: sudo

isa:
  children:
    isa_qal
  vars:
    debug: false

isa_qal:
  vars:
    debug: true
    deployment: qual
  hosts:
    isaqal09: {}
    isaqal10: {}
