all:
  vars:
    runenv: prod
    ansible_become: yes
    ansible_become_method: sudo

isa:
  children:
    isa_prod
  vars:
    debug: false

isa_prod:
  vars:
    debug: false
    deployment: prod
  hosts:
    isaprd09: {}
    isaprd10: {}
    isaprd11: {}
    #isaprd12: {}
