global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  file:
    directory: "/etc/traefik/dynamic"

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
