tls:
  certificates:
    - certFile: "/etc/traefik/ssl/cert.pem"
      keyFile: "/etc/traefik/ssl/privkey.pem"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/ssl/cert.pem"
        keyFile: "/etc/traefik/ssl/privkey.pem"

http:
  # Add the router
  routers:
    router0:
      entryPoints:
      - web
      middlewares:
      - isa-basic-auth
      service: service-isa
      rule: "PathPrefix(`/`)"
    router1:
      entryPoints:
      - websecure
      middlewares:
      - isa-basic-auth
      tls: {}
      service: service-isa
      rule: "PathPrefix(`/`)"

  # Add the middleware
  middlewares:
    isa-basic-auth:
      basicAuth:
        users: "{{ frontend.htpass }}"

  # Add the service
  services:
    service-isa:
      loadBalancer:
        servers:
        - url: http://prometheus:9090/
