install_path: '/srv/isa'
data_path: "/srv/isa/prometheus-data"

frontend:
  domain: isa-monitoring
  #domain: idev-fsd.ml
  #protocol: https
  #htpass: "{% set comma = joiner(', ') %}{% for cred in _noc_secrets.frontend.credentials %}{{ comma() }}{{ cred.user }}:{{ cred.pass | password_hash('bcrypt', _noc_secrets.frontend.salt) }}{% endfor %}"

# Docker
docker_engine_version: 1.7.1
docker_engine_rpm_release: 1
docker_engine_rpm_name: "docker-engine-{{ docker_engine_version }}-{{ docker_engine_rpm_release }}.el6.x86_64.rpm"
docker_engine_download_base_url: https://get.docker.com/rpm/1.7.1/centos-6/RPMS/x86_64/

docker_containers_cidr_range: 172.16.0.0/15

# Prometheus
# vars for prometheus
prometheus_port: 9090
prometheus_container_name: "prometheus"
prometheus_image: "prom/prometheus"
prometheus_version: "latest"