install_path: '/srv/isa'
prometheus_path: "{{ install_path }}/prometheus"
traefik_path: "{{ install_path }}/traefik"


_secrets_path: "/keybase/team/epfl_isa/ansible_isa_monitoring_{{ deployment }}_secrets.yml"
_isa_secrets: "{{ lookup('file', _secrets_path) | from_yaml }}"

frontend:
  htpass: "{% set comma = joiner(', ') %}{% for cred in _isa_secrets.frontend.credentials %}{{ comma() }}{{ cred.user }}:{{ cred.pass | password_hash('bcrypt', _isa_secrets.frontend.salt) }}{% endfor %}"

prod_ports:
  - "8443:443"

test_ports:
  - "8443:443"
  - "8080:8080"

ports: "{{ prod_ports if debug == false else test_ports }}"

# Docker
docker_engine_version: 1.7.1
docker_engine_rpm_release: 1
docker_engine_rpm_name: "docker-engine-{{ docker_engine_version }}-{{ docker_engine_rpm_release }}.el6.x86_64.rpm"
docker_engine_download_base_url: https://get.docker.com/rpm/1.7.1/centos-6/RPMS/x86_64/

# TODO: maybe we should probe this as a fact
# Obtainable with
# docker run --rm alpine ip route | perl -ne 'm/default via ([0-9.]+)/ && print "$1\n";'
docker_host_ip: 172.17.42.1
docker_containers_cidr_range: 172.16.0.0/15

# Prometheus
# vars for prometheus
prometheus_container_name: "prometheus"
prometheus_image: "prom/prometheus"
prometheus_version: "latest"

# Traefik
# vars file for idevfsd-traefik
traefik_container_name: traefik
traefik_image: traefik
traefik_version: latest
traefik_debug: "{{ debug }}" # By default it uses the global debug variable but we can activate here only traefik debug
