- name: Check if environment is set
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: ISA
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    - debug:
        msg: "{{ debug }}"
      tags: debug
    - debug:
        msg: "{{ ports }}"
      tags: debug
    - name: Install Python dependencies for Ansible
      import_tasks: ../tasks/ansible-deps.yml
      tags: deps
    - name: Install and run Docker
      import_tasks: ../tasks/docker.yml
      tags: docker
    - name: iptables rules
      import_tasks: ../tasks/iptables_rules.yml
      tags: iptables
    - name: Change apache conf
      include_tasks:
        file: ../tasks/apache-conf.yml
        apply:
          tags: apache_conf
      tags:
        - apache_conf
        - apache_conf.restart
    - name: Run apache exporter
      import_tasks: ../tasks/apache-exporter.yml
      tags: apache_exporter
    - name: Install and run prometheus
      import_tasks: ../tasks/prometheus.yml
      tags: prometheus
    - name: traefik
      import_tasks: ../tasks/traefik.yml
      tags: traefik
