- name: Check if environment is set
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: ISA
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    - name: Install and run Docker
      import_tasks: ../tasks/docker.yml
      tags: docker
