- name: Check if environment is set
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    -
      debug:
        msg: "Starting ansible with {{ runenv }} environment."

- name: ISA
  hosts: all
  gather_facts: no   # Not yet
  tasks:
    - name: Install Python dependencies for Ansible
      import_tasks: ../tasks/ansible-deps.yml
      tags: deps
    - name: Install and run Docker
      import_tasks: ../tasks/docker.yml
      tags: docker
    - name: Change apache conf
      import_tasks: ../tasks/apache-conf.yml
      tags: apache_conf
    - name: Run apache exporter
      import_tasks: ../tasks/apache-exporter.yml
      tags: apache_exporter
    - name: Install and run prometheus
      import_tasks: ../tasks/prometheus.yml
      tags: prometheus
