- name: Check if Apache already configures /server-status
  shell:
    cmd: |
      conf_has_string() {
        grep "$1" /etc/httpd/conf.d/EPFL_isa.conf
      }

      if conf_has_string "# BEGIN apache server status"; then exit 0; fi
      if conf_has_string "<Location /server-status>"; then exit 2; fi
      exit 0
  register: _server_status_block_present
  changed_when: false
  ignore_errors: true

- name: Set up .conf to serve status apache page
  when: not _server_status_block_present is failed
  blockinfile:
    path: "/etc/httpd/conf.d/EPFL_isa.conf"
    marker: "# {mark} apache server status"
    block: |
      <Location /server-status>
        SetHandler server-status
 
        Order Deny,Allow
        Deny from all
        Allow from 127.0.0.1
      </Location>
  register: _apache_config

- name: Check if apache proxy pass block is present in ssl.conf file
  shell:
    cmd: |
      result=$( cat /etc/httpd/conf.d/ssl.conf | grep "ProxyPass /prom/ http://127.0.0.1:8888/prom/" -A 4)
      if [result == ""]
      then
        echo 0
      else
        echo 1
      fi
  register: apache_proxypass_block_present

- debug:
    msg: "{{ apache_proxypass_block_present.stdout }}"

- name: Ensure that apache proxypass block is present
  when: not apache_proxypass_block_present.stdout
  blockinfile:
    path: "/etc/httpd/conf.d/ssl.conf"
    marker: "# {mark} apache proxypass block"
    block: |
      ProxyPass /prom/ http://127.0.0.1:8888/prom/
      ProxyPassReverse /prom/ http://127.0.0.1:8888/prom/
  
      ProxyPass /metrics http://127.0.0.1:9117/metrics
      ProxyPassReverse /metrics http://127.0.0.1:9117/metrics
- name: restart Apache
  tags: apache_conf.restart
  when: >-
    ( (_apache_config | default({})) is changed )
    or
    ('apache_conf.restart' in ansible_run_tags)
  command: |
    apachectl graceful
