- name: Run apache exporter
  community.docker.docker_container:
    name: apache_exporter
    image: solsson/prometheus-exporter-apache
    command: >-
      --scrape_uri="http://{{ docker_host_ip }}/server-status?auto"
