- name: Check if Apache already configures /server-status
  shell:
    cmd: |
      conf_has_string() {
        grep "$1" /etc/httpd/conf.d/EPFL_isa.conf
      }

      if conf_has_string "# BEGIN apache server status"; then exit 0; fi
      if conf_has_string "<Location /server-status>"; then exit 2; fi
      exit 0
  register: _server_status_block_present
  changed_when: false
  ignore_errors: true

- name: Set up Apache to serve status apache page
  when: not _server_status_block_present is failed
  blockinfile:
    path: "/etc/httpd/conf.d/EPFL_isa.conf"
    marker: "# {mark} apache server status"
    block: |
      <Location /server-status>
        SetHandler server-status
 
        Order Deny,Allow
        Deny from all
        # Allow from both Docker containers and localhost:
        Allow from 127.0.0.1 {{ docker_containers_cidr_range }}
        </Location>
  register: _apache_config

- name: restart Apache
  tags: apache_conf.restart
  when: >-
    ( (_apache_config | default({})) is changed )
    or
    ('apache_conf.restart' in ansible_run_tags)
  command: |
    apachectl graceful
