- name: Open port 8080
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8080"
    jump: ACCEPT
    action: insert
    rule_num: "5"
    state: "{{ 'absent' if debug == false else 'present' }}"

- name: Open port 8443
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8443"
    jump: ACCEPT
    action: insert
    rule_num: "5"
