- name: Open port 81
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 81
    jump: ACCEPT
    action: insert
    rule_num: 5

- name: Open port 8080
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8080
    jump: ACCEPT
    action: insert
    rule_num: 5

- name: Open port 8443
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8443
    jump: ACCEPT
    action: insert
    rule_num: 5
