# ------------------------------------------------------------------ Directories
- name: Create writable directories to be used as mount points
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - "{{ install_path }}/prometheus"
    - "{{ data_path }}/prometheus"

# -------------------------------------------------------------------- Templates
- name: Copy prometheus template configs
  template:
    src: "prometheus/{{ item }}"
    dest: "{{ install_path }}/prometheus/{{ item }}"
  with_items:
    - prometheus.yml
    #- rules/alert-all-the-time-for-tests.yml
    #- rules/c2c_federate.yml
  register: _prometheus_template_file

- name: Run prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    container_default_behavior: compatibility
    links:
      - apache_exporter
    command: >-
      --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - "{{ install_path }}/prometheus:/etc/prometheus"
      - "{{ data_path }}/prometheus:/prometheus"
