# ------------------------------------------------------------------ Directories
- name: Create writable directories to be used as mount points
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - "{{ install_path }}/prometheus"
    - "{{ data_path }}/prometheus"

# -------------------------------------------------------------------- Templates
- name: Copy prometheus template configs
  template:
    src: "prometheus/{{ item }}"
    dest: "{{ install_path }}/prometheus/{{ item }}"
  with_items:
    - prometheus.yml
    #- rules/alert-all-the-time-for-tests.yml
    #- rules/c2c_federate.yml
  register: _prometheus_template_file

- name: Run prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    links:
      - apache_exporter
    ports: 
      - "8888:9090"
    command: >-
      --config.file=/etc/prometheus/prometheus.yml
      --web.external-url=http://localhost:8888/prom
    volumes:
      - "{{ install_path }}/prometheus:/etc/prometheus"
      - "{{ data_path }}/prometheus:/prometheus"

#network_mode: "host"
#links:
#  - apache_exporter
#    networks:
#      - name: "epfl"
#--web.route-prefix=/prom/
#--web.external-url=https://isaqualite.epfl.ch/prom
    #  --web.route-prefix=/prom
    #- "{{ data_path }}/prometheus:/prometheus"
    # command: >-
    #   --config.file=/etc/prometheus/prometheus.yml
    #   --web.external-url=https://prometheus{{ dnspostfix }}.{{ frontend.domain }}
    #   {% if runenv == "isa_qal" %}
    #     --log.level=debug
    #   {% endif %}
    # detach: yes
    # restart_policy: unless-stopped
    
    # log_driver: json-file
    # log_options:
    #   max-size: 50m
    #   max-file: "3"
