- name: Create writable directories to be used as mount points
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - "{{ prometheus_path }}"
    - "{{ prometheus_path }}/data"

- name: Copy prometheus template configs
  template:
    src: "prometheus/{{ item }}"
    dest: "{{ prometheus_path }}/{{ item }}"
  with_items:
    - prometheus.yml
  register: _prometheus_template_file

- name: Run prometheus
  community.docker.docker_container:
    name: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}:{{ prometheus_version }}"
    container_default_behavior: compatibility
    links:
      - apache_exporter
    command: >-
      --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - "{{ prometheus_path }}:/etc/prometheus"
      - "{{ prometheus_path }}/data:/prometheus"
