- name: Generate private key if privkey.pem file doesn't exist
  command:
    chdir: /srv/isa/traefik/ssl/
    cmd: openssl genrsa -out privkey.pem 2048
    creates: /srv/isa/traefik/ssl/privkey.pem
  
- name: Generate certificat if cert.pem file doesn't exist
  command:
    chdir: /srv/isa/traefik/ssl/
    cmd: "openssl req -new -x509 -batch -subj \"/CN={{ inventory_hostname }}.epfl.ch\" -days 300000 -out cert.pem -key privkey.pem"
    creates: /srv/isa/traefik/ssl/cert.pem
